// WASM Runtime (v0.1 placeholder)
// Executes "WASM-ready" JS modules generated by KERN

class WasmRuntime {
  constructor(CompiledSPC) {
    this.app = new CompiledSPC();
  }

  async execute() {
    return await this.app.run();
  }
}

module.exports = WasmRuntime;

